### ISSUE TITLE
RNAseq data

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/RTCGA.data#1]
Could you add RNA-seq data as well?

**Comment by MarcinKosinski** [comment]
Yes, I'll try

**Comment by MarcinKosinski** [comment]
I've added rnaseq data but now pakage is a bit to large and I can't proceed with build.
![error](https://cloud.githubusercontent.com/assets/6773454/7809884/d7b978a0-039d-11e5-8a61-6848aa19cf75.png)

**Comment by MarcinKosinski** [comment]
But `.Rd` files in `data/` folder has only 550 MB. Strange
548 MB (bajtów: 575 505 365)

**Comment by MarcinKosinski** [comment]
Maybe it's a matter of my R session. I'll check that on another computer

**Comment by MarcinKosinski** [comment]
Ok, package installation proceed correctly.
