### ISSUE TITLE
MANUAL: Adding a new package to the `RTCGA.data` family

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/RTCGA.data#2]
When adding a new package to the  `RTCGA.data` family remember to proceed with few short steps

- 1. Add new package to a new folder with a name that is consistent with convention `RTCGA.*`, where `*` is a package name that suits the data that are included in this new package
- 2. Add a vignette to your new package (in `RTCGA.*/vignettes/` directory), that shows how the data to your new package were downloaded. Also you can add more vignettes with usage examples or use cases.
- 3. Add vignettes mentioned in the above point to the `ghPage` directory in the main directory of the whole `RTCGA.data` repository. **NEW**: The YAML of the `.Rmd` file should contain such command as output parameter (to include `before_body.html` file). Then compile the `.Rmd` file with vignette(s) so that there appears `.html` output for that vignette.
````{Ruby}
output: 
   html_document:
      fig_width: 17
      fig_height: 10
      toc: true
      toc_depth: 3
      theme: readable
      highlight: pygments
      keep_md: true
      includes:
         in_header: include/in_header.html
         before_body: include/before_body.html
````

- 4. Edit `ghPage/include/before_body.html` file, so that your vignettes would be added to a gh-page.
- 5. When new vignettes are added to `ghPage` and this file `ghPage/include/before_body.html` is edited, add new `.html` outputs for new vignettes and edited `ghPage/include/before_body.html` file to a `gh-page` branch, so that the gh-page of `RTCGA.data` repository updates with a new package: http://mi2-warsaw.github.io/RTCGA.data/ 
- 6. Remember to edit `README.md` file in master branch. Add yourself to *authors* section. Also remember to add information on how to install, load and use your package. Mainly edit those lines:
````{Ruby}
if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github("mi2-warsaw/RTCGA.data", 
               subdir = paste0("RTCGA.", 
                              c("clinical",
                                 "rnaseq",
                                 "mutations")
                                 )
               )
The list of available datasets:

library(RTCGA.clinical)
library(RTCGA.rnaseq)
library(RTCGA.mutations)
?clinical
?rnaseq
?mutations
````

- 7. Edit the same information as in the above point in `ghPage/index.Rmd` file, and remember to compile it to receive `.html` output, and then also copy+paste this new `index.html` file from `master` to `gh-page` branch.

**Comment by pbiecek** [comment]
should it be ghPage or ghPages? The directory in the root of RTCGA.data is ghPage.

**Comment by MarcinKosinski** [comment]
`ghPage`. I've edited my post

**Comment by pbiecek** [comment]
ok, thanks for instruction, I've added cnv and pancan12

**Comment by MarcinKosinski** [comment]
I've updated point 3 and re-rendered whole webpage http://mi2-warsaw.github.io/RTCGA.data/. Now all vignettes are in the same template. I am moving this issue to [wiki](https://github.com/mi2-warsaw/RTCGA.data/wiki/Contribution:-Adding-a-new-package-to-the-RTCGA.data-family):
