### ISSUE TITLE
Installation of packages from RTCGA.data family from RTCGA.data repo

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/RTCGA.data#3]
At the begging of this project I thought `install_github` function was vectorized over repository on a github. But it is vectorized of a `repo` as a parameter:

>
> This function is vectorised on repo so you can install multiple packages in a single command.
>

I though you can install many packages from one github repository during one download but it appears that this function is vectorized over repositories on github and you can download many packages from various repositories like this:
````{Ruby}
install_github(c("rstudio/httpuv", "rstudio/shiny"))
````
But for many packages within one github repository it behaves dumb. It downloades whole repository, install one package and removes repository and then downloads it again as it does not recognize that packages are within one repository.
Command like this (now it is vectorized over `repo` not over `subdir` as it was before [this commit](https://github.com/mi2-warsaw/RTCGA.data/commit/af17e0cbf2ebd6d955979bdac11b110f58ec87c6) @f38f079 #f38f079 )
````{Ruby}
if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github(paste0("mi2-warsaw/RTCGA.data/", 
                  subdir = paste0("RTCGA.", 
                                  c("clinical", "rnaseq",
                                    "mutations", "cnv", "PANCAN12")
                                 )))
````
download our heavy repository 5 times...
I've wrote about it on this stack [questio](http://stackoverflow.com/questions/31500893/vectorization-of-the-install-github-function-from-devtools-package-in-r). The solution by Dirk is to use [drat](http://dirk.eddelbuettel.com/code/drat.html) which can mimic mini-CRAN and maybe we should add packages separately to drat repository? What do you think about that?

For now one, even the correct version of the code for installation that is vectorized over `repo` parameter  does not install whole packages. When you install packages separately, you de facto download other 4 packages that are really heavy so it's not done in an optimal way.

We should reorganize packages distirbution. Any ideas beside drat? Maybe separate github repository for every package from `RTCGA.data` family?

**Comment by pbiecek** [comment]
GitHub download either a whole repository or a single file,
So an alternative solution is to create a tar.gz and .zip package bundles for each package in the family in a single directory. Then people can install the package directly though this single file.
E.g. adding directory 'repo' and place there tag.gz for each package from the family.
[along the way in which drat is working but without drat]

Other approach is to have different repositories for each package, what is maybe more convenient for most users.

**Comment by MarcinKosinski** [comment]
So in my opinion it would be betterto have `tar.gz`files in new directories, but does the `install_github` function or any other function would install compressed packages from that `tar.gz` files in a one single and simple function call?

**Comment by pbiecek** [comment]
I've tested RTCGA.cnv, and it's working with
library(devtools)
install_url("https://github.com/mi2-warsaw/RTCGA.data/raw/master/RTCGA.cnv_0.1.tar.gz")

**Comment by pbiecek** [comment]
Maybe it's safer to remove version from file name,
to use _package_name.tag.gz naming convention.
Otherwise one needs to change instructions every time the package version is changed

**Comment by MarcinKosinski** [comment]
Ok sounds and looks good to me :)

**Comment by pbiecek** [comment]
It turns out that the tar.gz for RTCGA.PANCAN12 is over 200MB
so it will not fit into github limits.

we can host it on mi2 http server


2015-07-20 15:00 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Ok sounds and looks good to me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mi2-warsaw/RTCGA.data/issues/3#issuecomment-122876549>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Or maybe should we publicate packages on a bioconductor?

**Comment by pbiecek** [comment]
good idea

2015-07-20 15:45 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Or maybe should we publicate packages on a bioconductor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mi2-warsaw/RTCGA.data/issues/3#issuecomment-122890207>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
packages are being revised on a bioconductor
